apiVersion: v1
kind: ConfigMap
metadata:
  name: minio-config
  namespace: default
  labels:
    app: minio
data:
  # MinIO bucket name
  MINIO_BUCKET: "netmind"

  # cors.json — mount vào minio-init Job
  cors.json: |
    {
      "CORSRules": [
        {
          "AllowedHeaders": ["*"],
          "AllowedMethods": ["GET", "PUT", "POST", "DELETE", "HEAD"],
          "AllowedOrigins": ["*"],
          "ExposeHeaders": ["ETag", "Content-Length", "Content-Type"],
          "MaxAgeSeconds": 3600
        }
      ]
    }
