apiVersion: v1
kind: Secret
metadata:
  name: monitoring-secret
  namespace: default
  labels:
    app: grafana
type: Opaque
stringData:
  GF_SECURITY_ADMIN_PASSWORD: "123456"

# --- Tạo bằng kubectl ---
# kubectl create secret generic monitoring-secret \
#   --from-literal=GF_SECURITY_ADMIN_PASSWORD=<value> \
#   --namespace=default
