apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: uploads-data
  namespace: default
  labels:
    app: docai
spec:
  accessModes:
    - ReadWriteMany   # Cần RWX vì backend + platform-worker cùng mount
  storageClassName: rook-cephfs
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: temp-data
  namespace: default
  labels:
    app: docai
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: rook-cephfs
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: output-data
  namespace: default
  labels:
    app: docai
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: rook-cephfs
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: logs-data
  namespace: default
  labels:
    app: docai
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: rook-cephfs
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: docprocess-workspace
  namespace: default
  labels:
    app: docai
spec:
  accessModes:
    - ReadWriteOnce   # Chỉ docprocess-worker dùng
  storageClassName: rook-ceph-block
  resources:
    requests:
      storage: 2Gi
